---
Transform: AWS::Serverless-2016-10-31

Description: |
  A bucket that responds with pongs when pinged

Metadata:
  iam_capabilities:
    - CAPABILITY_IAM

Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "{{ bucket_name }}"

  EventHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Process S3 events
      Handler: index.handler
      CodeUri: "{{ lambda_uri('s3-event-handler') }}"
      Runtime: python3.6
      Events:
        ObjectCreate:
          Type: S3
          Properties:
            Bucket: !Ref TestBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .ping
      MemorySize: 128
      Timeout: 5
      Policies:
      - S3CrudPolicy:
          BucketName: "{{ bucket_name }}"